key: JKNet_Reddit


# -------datasets-------
Planetoid: &Planetoid
  task: transductive
  pre_transform: HomophilyRank()
  split: public
  n_tri: 10

Cora: &Cora
  dataset: Cora
  <<: *Planetoid
  transform: None
  n_feat: 1433
  n_class: 7

CiteSeer: &CiteSeer
  dataset: CiteSeer
  <<: *Planetoid
  transform: T.NormalizeFeatures()
  n_feat: 3703
  n_class: 6

PubMed: &PubMed
  dataset: PubMed
  <<: *Planetoid
  transform: None
  n_feat: 500
  n_class: 3

Reddit: &Reddit
  task: transductive
  dataset: Reddit
  pre_transform: None
  transform: None
  n_feat: 602
  n_class: 41
  n_tri: 10
  epochs: 20 # override >> GNN
  learning_rate: 0.01
  weight_decay: 0.
  dropout: 0.5

FiveUniqNodes: &FiveUniqNodes
  task: transductive  
  dataset: FiveUniqNodes
  pre_transform: HomophilyRank()
  split: public
  transform: None
  n_feat: 2
  n_class: 2
  n_tri: 30

PPI: &PPI
  task: inductive
  dataset: PPI
  pre_transform: None
  transform: None
  n_feat: 50
  n_class: 121
  n_tri: 1
  learning_rate: 0.005
  weight_decay: 0.    
  dropout: 0.

  
# -------models-------
GNN: &GNN
  seed: 42
  epochs: 200
  patience: 100
  learning_rate: 0.01
  weight_decay: 0.0005
  dropout: 0.5


GCN: &GCN
  <<: *GNN
  model: GCN
  n_hid: [16]

GCN_Cora: &GCN_Cora
  <<: [*Cora, *GCN]

GCN_CiteSeer: &GCN_CiteSeer
  <<: [*CiteSeer, *GCN]

GCN_PubMed: &GCN_PubMed
  <<: [*PubMed, *GCN]

GCN_PPI: &GCN_PPI
  <<: [*PPI, *GCN]
  n_hid: [256, 256] # override >> GCN

GCN_toy: &GCN_toy
  <<: [*FiveUniqNodes, *GCN]
  n_hid: [2] # override >> GCN


GATNet: &GATNet
  <<: *GNN
  model: GATNet
  n_hid: [8]
  n_head: [1,8,1]
  iscat: [False,True,False]
  weight_decay: 0.001
  dropout: 0.6 # override >> GNN

GATNet_Cora: &GATNet_Cora
  <<: [*Cora, *GATNet]
  transform: T.NormalizeFeatures() # override >> Cora

GATNet_CiteSeer: &GATNet_CiteSeer
  <<: [*CiteSeer, *GATNet]

GATNet_PubMed: &GATNet_PubMed
  <<: [*PubMed, *GATNet]
  split: 'public'
  weight_decay: 0.001 # override >> GNN
  n_head: [1,8,8] # override >> GATNet
  iscat: [False,True,False] # override >> GATNet

GATNet_PubMed_Super: &GATNet_PubMed_Supervised
  <<: [*PubMed, *GATNet]
  split: 'full'

GATNet_PPI: &GATNet_PPI
  <<: [*PPI, *GATNet]
  n_hid: [256,256]  # override >> GATNet
  n_head: [1,4,4,6] # override >> GATNet
  iscat: [False,True,True,False] # override >> GATNet

GATNet_toy: &GATNet_toy
  <<: [*FiveUniqNodes, *GATNet]
  dropout: 0.2 # override >> GNN
  n_hid:  [2,2] # override >> GATNet
  n_head: [1,1,1,1] # override >> GATNet
  iscat:  [False,False,False,False] # override >> GATNet


JKNet: &JKNet
  <<: *GNN
  model: JKNet_GCNConv
  learning_rate: 0.005 # override >> GNN
  n_layer: 6
  n_hid: 16

JKNet_Cora: &JKNet_Cora
  <<: [*Cora, *JKNet]
  jk_mode: max
  att_mode: go # this works iff jk_mode is lstm, ['go', 'sd', 'mx']

JKNet_CiteSeer: &JKNet_CiteSeer
  <<: [*CiteSeer, *JKNet]
  n_layer: 1 # override >> JKNet
  jk_mode: cat
  att_mode: go # this works iff jk_mode is lstm, ['go', 'sd', 'mx']

JKNet_PubMed: &JKNet_PubMed
  <<: [*PubMed, *JKNet]
  jk_mode: max
  att_mode: go # this works iff jk_mode is lstm, ['go', 'sd', 'mx']
  
JKNet_Reddit: &JKNet_Reddit
  <<: [*Reddit, *JKNet]
  model: JKNet_SAGEConv # override >> JKNet
  n_layer: 2
  n_hid: 256
  jk_mode: lstm
  att_mode: go
  isdense: False

JKNet_PPI: &JKNet_PPI
  <<: [*PPI, *JKNet]
  model: JKNet_GATConv # override >> JKNet
  n_layer: 3
  n_hid: 256
  n_head: 4
  iscat: True
  jk_mode: lstm
  att_mode: go
  isdense: False

JKNet_toy: &JKNet_toy
  <<: [*FiveUniqNodes, *JKNet]
  learning_rate: 0.01 # override >> JKNet
  dropout: 0.2
  n_hid: 2 # override >> JKNet
  n_layer: 3 # override >> JKNet
  jk_mode: lstm
  att_mode: go # this works iff jk_mode is lstm, ['go', 'sd', 'mx']


UniqGCN: &UniqGCN
  <<: *GNN
  model: UniqGCN
  n_hid: 32

UniqGCN_Cora: &UniqGCN_Cora
  <<: [*Cora, *UniqGCN]
  n_layer: 10

UniqGCN_CiteSeer: &UniqGCN_CiteSeer
  <<: [*CiteSeer, *UniqGCN]
  n_layer: 10

UniqGCN_PubMed: &UniqGCN_PubMed
  <<: [*PubMed, *UniqGCN]
  n_layer: 10

UniqGCN_PPI: &UniqGCN_PPI
  <<: [*PPI, *UniqGCN]
  n_layer: 3
  n_hid: 256
  n_head: 4
  iscat: True
  jk_mode: lstm
  att_mode: go

UniqGCN_toy: &UniqGCN_toy
  <<: [*FiveUniqNodes, *UniqGCN]
  n_layer: 7
  n_hid: 2 # override >> UniqGCN
