key: GCN_Cora


# -------datasets-------
Planetoid: &Planetoid
  pre_transform: HomophilyRank()
  split: 'public'
  n_tri: 10

Cora: &Cora
  <<: *Planetoid
  dataset: Cora
  n_feat: 1433
  n_class: 7
  transform: None

CiteSeer: &CiteSeer
  <<: *Planetoid
  dataset: CiteSeer
  n_feat: 3703
  n_class: 6
  transform: T.NormalizeFeatures()

PubMed: &PubMed
  <<: *Planetoid
  dataset: PubMed
  n_feat: 500
  n_class: 3
  transform: None

FiveUniqNodes: &FiveUniqNodes
  dataset: FiveUniqNodes
  n_feat: 2
  n_class: 2
  n_tri: 10

  
# -------models-------
GNN: &GNN
  seed: 42
  epochs: 200
  patience: 100
  learning_rate: 0.01
  weight_decay: 0.0005
  dropout: 0.5


GCN: &GCN
  <<: *GNN
  model: GCN
  n_hid: [16]

GCN_Cora: &GCN_Cora
  <<: [*GCN, *Cora]

GCN_CiteSeer: &GCN_CiteSeer
  <<: [*GCN, *CiteSeer]

GCN_PubMed: &GCN_PubMed
  <<: [*GCN, *PubMed]

GCN_toy: &GCN_toy
  <<: [*GCN, *FiveUniqNodes]
  n_hid: [2] # override >> GCN


GATNet: &GATNet
  <<: *GNN
  model: GATNet
  n_hid: [8]
  n_head: [1,8,1]
  iscat: [False,True,False]
  dropout: 0.6 # override >> GNN

GATNet_Cora: &GATNet_Cora
  <<: [*GATNet, *Cora]
  transform: T.NormalizeFeatures() # override >> Cora

GATNet_CiteSeer: &GATNet_CiteSeer
  <<: [*GATNet, *CiteSeer]

GATNet_PubMed: &GATNet_PubMed
  <<: [*GATNet, *PubMed]
  split: 'public'
  weight_decay: 0.001 # override >> GNN
  n_head: [1,8,8] # override >> GATNet
  iscat: [False,True,False] # override >> GATNet

GATNet_PubMed_Super: &GATNet_PubMed_Super
  <<: [*GATNet, *PubMed]
  split: 'full'

GATNet_toy: &GATNet_toy
  <<: [*GATNet, *FiveUniqNodes]
  dropout: 0.2 # override >> GNN
  n_hid:  [2,2] # override >> GATNet
  n_head: [1,1,1,1] # override >> GATNet
  iscat:  [False,False,False,False] # override >> GATNet


JKNet: &JKNet
  <<: *GNN
  model: JKNet
  learning_rate: 0.005 # override >> GNN
  n_hid: 32
  n_layer: 6

JKNet_Cora: &JKNet_Cora
  <<: [*JKNet, *Cora]
  jk_mode: max

JKNet_CiteSeer: &JKNet_CiteSeer
  <<: [*JKNet, *CiteSeer]
  jk_mode: cat

JKNet_PubMed: &JKNet_PubMed
  <<: [*JKNet, *PubMed]
  jk_mode: max

JKNet_toy: &JKNet_toy
  <<: [*JKNet, *FiveUniqNodes]
  learning_rate: 0.01 # override >> JKNet
  n_hid: 2 # override >> JKNet
  jk_mode: lstm
  att_mode: sd # this works iff jk_mode is lstm, ['go', 'sd', 'mx']


UniqGCN: &UniqGCN
  <<: *GNN
  model: UniqGCN
  n_hid: 32

UniqGCN_Cora: &UniqGCN_Cora
  <<: [*UniqGCN, *Cora]
  n_layer: 10

UniqGCN_CiteSeer: &UniqGCN_CiteSeer
  <<: [*UniqGCN, *CiteSeer]
  n_layer: 10

UniqGCN_PubMed: &UniqGCN_PubMed
  <<: [*UniqGCN, *PubMed]
  n_layer: 10

UniqGCN_toy: &UniqGCN_toy
  <<: [*UniqGCN, *FiveUniqNodes]
  n_hid: 2 # override >> UniqGCN
  n_layer: 7