# -------datasets-------
Cora: &Cora
  dataset: Cora
  norm: None

CiteSeer: &CiteSeer
  dataset: CiteSeer
  norm: T.NormalizeFeatures()

PubMed: &PubMed
  dataset: PubMed
  norm: None

FiveUniqueNodes: &FiveUniqueNodes
  dataset: FiveUniqueNodes
  n_tri: 100

  
# -------models-------
GNN: &GNN
  split: 'full_60per'
  n_tri: 10
  seed: 42
  epochs: 200
  patience: 100
  learning_rate: 0.01
  weight_decay: 0.0005
  dropout: 0.5


GCN: &GCN
  <<: *GNN
  model: GCN
  n_hid: [16]

GCN_Cora: &GCN_Cora
  <<: *GCN
  <<: *Cora

GCN_CiteSeer: &GCN_CiteSeer
  <<: *GCN
  <<: *CiteSeer

GCN_PubMed: &GCN_PubMed
  <<: *GCN
  <<: *PubMed

GCN_toy: &GCN_toy
  <<: *GCN
  <<: *FiveUniqueNodes
  n_hid: [2] # override >> GCN


GATNet: &GATNet
  <<: *GNN
  model: GATNet
  n_hid: [8]
  n_head: [1,8,1]
  iscat: [False,True,False]
  dropout: 0.6 # override >> GNN

GATNet_Cora: &GATNet_Cora
  <<: *GATNet
  <<: *Cora
  norm: T.NormalizeFeatures() # override >> Cora

GATNet_CiteSeer: &GATNet_CiteSeer
  <<: *GATNet
  <<: *CiteSeer

GATNet_PubMed: &GATNet_PubMed
  <<: *GATNet
  <<: *PubMed
  split: 'public'
  weight_decay: 0.001 # override >> GNN
  n_head: [1,8,8] # override >> GATNet
  iscat: [False,True,False] # override >> GATNet

GATNet_PubMed_Super: &GATNet_PubMed_Super
  <<: *GATNet
  <<: *PubMed
  split: 'full'

GATNet_toy: &GATNet_toy
  <<: *GATNet
  <<: *FiveUniqueNodes
  dropout: 0.2 # override >> GNN
  n_hid:  [2,2] # override >> GATNet
  n_head: [1,1,1,1] # override >> GATNet
  iscat:  [False,False,False,False] # override >> GATNet


JKNet: &JKNet
  <<: *GNN
  model: JKNet
  learning_rate: 0.005 # override >> GNN
  n_hid: 32

JKNet_Cora: &JKNet_Cora
  <<: *JKNet
  <<: *Cora
  n_layer: 6
  jk_mode: lstm

JKNet_CiteSeer: &JKNet_CiteSeer
  <<: *JKNet
  <<: *CiteSeer
  n_layer: 1
  jk_mode: cat

JKNet_PubMed: &JKNet_PubMed
  <<: *JKNet
  <<: *PubMed
  n_layer: 6
  jk_mode: max

JKNet_toy: &JKNet_toy
  <<: *JKNet
  <<: *FiveUniqueNodes
  learning_rate: 0.01 # override >> JKNet
  n_layer: 6
  jk_mode: cat


UniqGCN: &UniqGCN
  <<: *GNN
  model: UniqGCN
  n_hid: 16

UniqGCN_Cora: &UniqGCN_Cora
  <<: *UniqGCN
  <<: *Cora
  n_layer: 6

UniqGCN_CiteSeer: &UniqGCN_CiteSeer
  <<: *UniqGCN
  <<: *CiteSeer
  n_layer: 10

UniqGCN_PubMed: &UniqGCN_PubMed
  <<: *UniqGCN
  <<: *PubMed
  n_layer: 10

UniqGCN_toy: &UniqGCN_toy
  <<: *UniqGCN
  <<: *FiveUniqueNodes
  n_hid: 2 # override >> UniqGCN
  n_layer: 7