IFS_BACKUP=$IFS
IFS=$'\n'

ary=("python3 train_ogb_proteins.py -m 'hydra.sweeper.n_trials=135' 'key=AttGNN_OGBproteins' 'mlflow.runname=AttGNN_OGBproteins' 'AttGNN_OGBproteins.n_tri=5' 'AttGNN_OGBproteins.epochs=1000' 'AttGNN_OGBproteins.learning_rate=0.01' 'AttGNN_OGBproteins.weight_decay=0.' 'AttGNN_OGBproteins.dropout=0.' 'AttGNN_OGBproteins.n_layer=range(2,6)' 'AttGNN_OGBproteins.n_hid=256' 'AttGNN_OGBproteins.summary_mode=choice(vanilla,roll,lstm)' 'AttGNN_OGBproteins.att_mode=choice(ad,dp,mx)' 'AttGNN_OGBarxiv.norm=choice(None,LayerNorm,BatchNorm1d)'")

for STR in ${ary[@]}
do
    eval "${STR}"
done


# ----template----
# Cora        python3 train_planetoid.py -m 'hydra.sweeper.n_trials=500' 'key=AttGNN_Cora' 'mlflow.runname=AttGNN_Cora' 'AttGNN_Cora.learning_rate=choice(0.01,0.005,0.001)' 'AttGNN_Cora.weight_decay=choice(0.001,0.0005,0.0001,0.)' 'AttGNN_Cora.dropout=choice(0.6,0.5,0.)' 'AttGNN_Cora.n_layer=range(2,6)' 'AttGNN_Cora.att_mode=choice('ad','mx','dp')' 'AttGNN_Cora.att_temparature=interval(-1.,1.)'
# CiteSeer    python3 train_planetoid.py -m 'hydra.sweeper.n_trials=500' 'key=AttGNN_CiteSeer' 'mlflow.runname=AttGNN_CiteSeer' 'AttGNN_CiteSeer.learning_rate=choice(0.01,0.005,0.001)' 'AttGNN_Cora.weight_decay=choice(0.001,0.0005,0.0001,0.)' 'AttGNN_CiteSeer.dropout=choice(0.6,0.5,0.)' 'AttGNN_CiteSeer.n_layer=range(2,6)' 'AttGNN_CiteSeer.att_mode=choice('ad','mx','dp')' 'AttGNN_CiteSeer.att_temparature=interval(-1.,1.)'
# PubMed      python3 train_planetoid.py -m 'hydra.sweeper.n_trials=100' 'key=AttGNN_PubMed' 'mlflow.runname=AttGNN_PubMed' 'AttGNN_PubMed.learning_rate=choice(0.01,0.005,0.001)' 'AttGNN_PubMed.weight_decay=choice(0.001,0.0005,0.0001,0.)' 'AttGNN_PubMed.dropout=choice(0.6,0.5,0.)' 'AttGNN_PubMed.n_layer=range(2,6)' 'AttGNN_PubMed.att_mode=choice('ad','mx','dp')' 'AttGNN_PubMed.att_temparature=interval(-1.,1.)'
# PPI         python3 train_ppi.py -m 'hydra.sweeper.n_trials=100' 'key=AttGNN_PPI' 'mlflow.runname=AttGNN_PPI' 'AttGNN_PPI.learning_rate=choice(0.01,0.005,0.001)' 'AttGNN_PPI.weight_decay=choice(0.001,0.0005,0.0001,0.)' 'AttGNN_PPI.dropout=choice(0.6,0.5,0.)' 'AttGNN_PPI.n_layer=range(2,6)' 'AttGNN_PPI.att_mode=choice('ad','mx','dp')' 'AttGNN_PPI.att_temparature=interval(-1.,1.)'
# Reddit      python3 train_reddit.py -m 'hydra.sweeper.n_trials=50' 'key=AttGNN_Reddit' 'mlflow.runname=AttGNN_Reddit_summarizer' 'AttGNN_Reddit.n_tri=5' 'AttGNN_Reddit.epochs=20' 'AttGNN_Reddit.learning_rate=0.001' 'AttGNN_Reddit.weight_decay=0.' 'AttGNN_Reddit.dropout=0.' 'AttGNN_Reddit.n_layer=2' 'AttGNN_Reddit.n_hid=128' 'AttGNN_Reddit.summary_mode=choice('vanilla', 'roll', 'lstm')' 'AttGNN_Reddit.att_mode=choice('ad','mx','dp')' 'AttGNN_Reddit.att_temparature=interval(-1.,1.)'
# OGBproteins python3 train_ogb_proteins.py -m 'hydra.sweeper.n_trials=50' 'key=AttGNN_OGBproteins' 'mlflow.runname=AttGNN_OGBproteins_summarizer' 'AttGNN_OGBproteins.n_tri=3' 'AttGNN_OGBproteins.epochs=1000' 'AttGNN_OGBproteins.learning_rate=0.01' 'AttGNN_OGBproteins.weight_decay=0.' 'AttGNN_OGBproteins.dropout=0.' 'AttGNN_OGBproteins.n_layer=3' 'AttGNN_OGBproteins.n_hid=256' 'AttGNN_OGBproteins.summary_mode=lstm' 'AttGNN_OGBproteins.att_mode=ad' 'AttGNN_OGBproteins.att_temparature=1.'
# OGBarxiv    python3 train_ogb_arxiv.py -m 'hydra.sweeper.n_trials=300' 'key=AttGNN_OGBarxiv' 'mlflow.runname=AttGNN_OGBarxiv' 'AttGNN_OGBarxiv.n_tri=5' 'AttGNN_OGBarxiv.epochs=500' 'AttGNN_OGBarxiv.learning_rate=choice(0.01,0.005,0.001)' 'AttGNN_OGBarxiv.weight_decay=choice(0.001,0.0005,0.0001,0.)' 'AttGNN_OGBarxiv.dropout=choice(0.6,0.5,0.)' 'AttGNN_OGBarxiv.n_layer=range(2,6)' 'AttGNN_OGBarxiv.n_hid=choice(128,256)' 'AttGNN_OGBarxiv.summary_mode=choice(vanilla,roll)' 'AttGNN_OGBarxiv.att_mode=choice(ad,dp,mx)'