key: AttGNN_Cora


# -------hydra & mlflow & optuna-------
mlflow: 
  runname: test

defaults:
  - override hydra/sweeper: optuna

hydra:
  sweeper:
    sampler:
      _target_: optuna.samplers.TPESampler
    direction: maximize
    n_jobs: 1
    n_trials: 10
    # search_space:
    #   AttGNN_PPI.learning_rate:
    #     type: categorical
    #     choices:
    #     - 0.01
    #     - 0.005
    #     - 0.001
    #   AttGNN_PPI.weight_decay:
    #     type: categorical
    #     choices:
    #     - 0.001
    #     - 0.0005
    #     - 0.0001
    #     - 0.
    #   AttGNN_PPI.dropout:
    #     type: categorical
    #     choices:
    #     - 0.6
    #     - 0.5
    #     - 0.
    #   AttGNN_PPI.n_layer:
    #     type: categorical
    #     choices:
    #     - ?
    #   AttGNN_PPI.n_hid:
    #     type: categorical
    #     choices:
    #     - ?
    #   AttGNN_PPI.summary_mode:
    #     type: categorical
    #     choices:
    #     - vanilla
    #     - roll
    #     - lstm
    #   AttGNN_PPI.att_mode:
    #     type: categorical
    #     choices:
    #     - ad
    #     - mx
    #     - dp
    #   AttGNN_PPI.att_temparature:
    #     type: categorical
    #     choices:
    #     - -0.6~0.6


# -------datasets-------
Planetoid: &Planetoid
  task: transductive
  pre_transform: None
  split: public
  n_tri: 10

Cora: &Cora
  dataset: Cora
  <<: *Planetoid
  transform: None
  n_feat: 1433
  n_class: 7

CiteSeer: &CiteSeer
  dataset: CiteSeer
  <<: *Planetoid
  transform: T.NormalizeFeatures()
  n_feat: 3703
  n_class: 6

PubMed: &PubMed
  dataset: PubMed
  <<: *Planetoid
  transform: None
  n_feat: 500
  n_class: 3

Reddit: &Reddit
  task: transductive
  dataset: Reddit
  pre_transform: None
  transform: None
  n_feat: 602
  n_class: 41
  n_tri: 5
  epochs: 20 # override >> GNN
  learning_rate: 0.01
  weight_decay: 0.
  dropout: 0.5

FiveUniqNodes: &FiveUniqNodes
  task: transductive  
  dataset: FiveUniqNodes
  pre_transform: HomophilyRank()
  split: public
  transform: None
  n_feat: 2
  n_class: 2
  n_tri: 30

PPI: &PPI
  task: inductive
  dataset: PPI
  pre_transform: None
  transform: None
  n_feat: 50
  n_class: 121
  n_tri: 5
  learning_rate: 0.005
  weight_decay: 0.    
  dropout: 0.

OGB: &OGB
  task: transductive
  n_tri: 3

OGBproteins: &OGBproteins
  dataset: OGBproteins
  <<: *OGB
  n_feat: 1
  e_feat: 8
  n_class: 112

OGBarxiv: &OGBarxiv
  dataset: OGBarxiv
  <<: *OGB
  n_feat: 128
  n_class: 40
  
# -------models-------
GNN: &GNN
  seed: 42
  epochs: 200
  patience: 100
  learning_rate: 0.01
  weight_decay: 0.0005
  dropout: 0.5


GCN: &GCN
  <<: *GNN
  model: GCN
  n_hid: [16]

GCN_Cora: &GCN_Cora
  <<: [*Cora, *GCN]

GCN_CiteSeer: &GCN_CiteSeer
  <<: [*CiteSeer, *GCN]

GCN_PubMed: &GCN_PubMed
  <<: [*PubMed, *GCN]

GCN_PPI: &GCN_PPI
  <<: [*PPI, *GCN]
  n_hid: [256, 256] # override >> GCN

GCN_toy: &GCN_toy
  <<: [*FiveUniqNodes, *GCN]
  n_hid: [2] # override >> GCN


GATNet: &GATNet
  <<: *GNN
  model: GATNet
  n_hid: [8]
  n_head: [1,8,1]
  iscat: [False,True,False]
  weight_decay: 0.001
  dropout: 0.6 # override >> GNN

GATNet_Cora: &GATNet_Cora
  <<: [*Cora, *GATNet]
  transform: T.NormalizeFeatures() # override >> Cora

GATNet_CiteSeer: &GATNet_CiteSeer
  <<: [*CiteSeer, *GATNet]

GATNet_PubMed: &GATNet_PubMed
  <<: [*PubMed, *GATNet]
  split: 'public'
  weight_decay: 0.001 # override >> GNN
  n_head: [1,8,8] # override >> GATNet
  iscat: [False,True,False] # override >> GATNet

GATNet_PubMed_Super: &GATNet_PubMed_Supervised
  <<: [*PubMed, *GATNet]
  split: 'full'

GATNet_PPI: &GATNet_PPI
  <<: [*PPI, *GATNet]
  n_hid: [256,256]  # override >> GATNet
  n_head: [1,4,4,6] # override >> GATNet
  iscat: [False,True,True,False] # override >> GATNet

GATNet_toy: &GATNet_toy
  <<: [*FiveUniqNodes, *GATNet]
  dropout: 0.2 # override >> GNN
  n_hid:  [2,2] # override >> GATNet
  n_head: [1,1,1,1] # override >> GATNet
  iscat:  [False,False,False,False] # override >> GATNet


AttGNN: &AttGNN
  <<: *GNN
  model: AttGNN
  learning_rate: 0.005 # override >> GNN
  n_layer: 6
  n_hid: 32
  norm: None # [None, LayerNorm, BatchNorm1d]
  self_node: True
  summary_mode: roll # [vanilla, roll, lstm]
  att_mode: ad # [ad, dp, wdp, mx]
  att_temparature: 1. # if set to 1, default attention of Summarize
  learn_temparature: False

AttGNN_Cora: &AttGNN_Cora
  <<: [*Cora, *AttGNN]
  base_gnn: GCN

AttGNN_CiteSeer: &AttGNN_CiteSeer
  <<: [*CiteSeer, *AttGNN]
  base_gnn: GCN

AttGNN_PubMed: &AttGNN_PubMed
  <<: [*PubMed, *AttGNN]
  base_gnn: GCN
  
AttGNN_Reddit: &AttGNN_Reddit
  <<: [*Reddit, *AttGNN]
  base_gnn: SAGE
  n_hid: 128 # override >> AttGNN

AttGNN_PPI: &AttGNN_PPI
  <<: [*PPI, *AttGNN]
  base_gnn: GAT
  n_hid: 128 # override >> AttGNN
  n_head: 4
  iscat: True

AttGNN_toy: &AttGNN_toy
  <<: [*FiveUniqNodes, *AttGNN]
  learning_rate: 0.01 # override >> AttGNN
  dropout: 0.2
  n_hid: 2 # override >> AttGNN
  n_layer: 3 # override >> AttGNN
  att_mode: ad

AttGNN_OGBproteins: &AttGNN_OGBproteins
  <<: [*OGBproteins, *AttGNN]
  base_gnn: GCN
  n_hid: 256 # override >> AttGNN
  norm: LayerNorm # override >> AttGNN

AttGNN_OGBarxiv: &AttGNN_OGBarxiv
  <<: [*OGBarxiv, *AttGNN]
  base_gnn: GCN
  n_hid: 128 # override >> AttGNN
  norm: LayerNorm # override >> AttGNN


UniqGCN: &UniqGCN
  <<: *GNN
  model: UniqGCN
  n_hid: 32

UniqGCN_Cora: &UniqGCN_Cora
  <<: [*Cora, *UniqGCN]
  n_layer: 10

UniqGCN_CiteSeer: &UniqGCN_CiteSeer
  <<: [*CiteSeer, *UniqGCN]
  n_layer: 10

UniqGCN_PubMed: &UniqGCN_PubMed
  <<: [*PubMed, *UniqGCN]
  n_layer: 10

UniqGCN_PPI: &UniqGCN_PPI
  <<: [*PPI, *UniqGCN]
  n_layer: 3
  n_hid: 256
  n_head: 4
  iscat: True
  summary_mode: lstm
  att_mode: ad

UniqGCN_toy: &UniqGCN_toy
  <<: [*FiveUniqNodes, *UniqGCN]
  n_layer: 7
  n_hid: 2 # override >> UniqGCN
